server:
  port: 8100
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/departments
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    stream:
      bindings:
        output:
          destination: departments
          content-type: application/json